In [12]:
idd = 0
meanrgb, stdrgb = [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]


import torch
import torch.nn as nn

from torch.utils.data import  random_split as slices
# dataloader takes the train set and is a abstraction over a class that provides batches of the dataset when used in a for loop. It 
# breaks the data set into batches of mentioned batchsize.
# random_split is used to split data into training , validation,test set
import torchvision as biglight
#T will be used to apply transformations like resizing image, normalizing, greyscale conversion etc.
from torchvision.datasets import FashionMNIST
# we will  be downloading FashionMNIST data from amazon
from torch.nn import Sequential as bunchoflayers
from torchvision.models import vgg16 as inbuiltmodel
import pickle, gc
# nn stands for neural network. It provides activation layers, cnn layers, linear layers etc.
from torch.utils.data import DataLoader as abcd
import numpy as np
# with this we import numpy module
import pandas as pd
# with this we import pandas module
collectiveset = 100
random_seed = 0
torch.manual_seed(random_seed)
applychanges = biglight.transforms.Compose([biglight.transforms.Resize(size=224), biglight.transforms.Grayscale(num_output_channels=3), biglight.transforms.ToTensor(), biglight.transforms.Normalize(meanrgb, stdrgb)])
# biglight.transforms.Resize resizes the image to 224X224
# biglight.transforms.Grayscale converts the image to greyscale
# biglight.transforms.ToTensor converts the image/np array to tensor
# biglight.transforms.Normalize normalizes the images using mean and std. of imagenet dataset. 3 means because of 3 colors: R,G,B

directory = './data'
tplusv = FashionMNIST(root=directory, download=True, transform=applychanges)



In [ ]:
# a torch dataset is made of tuples of the form (Tensor, number). A tensor is  like a numpy array
# open 10. 60,000/(batchsize * 10)

In [ ]:
train1s, train2s, train3s = (idd*6000), 6000, (6000*(9-idd)) 

train1, train2, train3 = slices(tplusv, [train1s, train2s, train3s], generator=torch.Generator().manual_seed(42))
del train1
del train3
gc.collect()
 

print("Training Data Size:", len(train2))
 
abstrationtrain = abcd(train2, batch_size=collectiveset, shuffle=False, num_workers=2, pin_memory=True)
# num_workers indicate how many processes to use for loading data
# pin_memory puts dataset in cuda memory
model = inbuiltmodel(pretrained=True)
model.classifier = nn.Identity()

#preprocess the output
print("total iterations"+str(len(train2)/collectiveset))
for ii, (data, target) in enumerate(abstrationtrain):
  print(ii)
  output1 = model.features(data)
  output1 = model.avgpool(output1)
  pickle.dump( output1, open(str((idd*60)+ii)+"batch_train.sav", "wb"))
 
  del output1
  gc.collect() 
 


Training Data Size: 6000
total iterations60.0
0


KeyboardInterrupt: ignored

In [ ]:
for i in range(idd*60, (idd+1)*60):
  cmd = 'cp '+str(i)+'batch_train.sav drive/MyDrive/sem6/mlass2/'+str(i)+'batch_train.sav'
  os.system(cmd)

In [13]:
def loads(samples):
  x = abcd(samples,
  batch_size=collectiveset,
  shuffle=notenablecuda,
  num_workers=noprocesses,
  pin_memory=enablecuda)
  return x
train_size, val_size, test_size = 43200, 10800, 6000
trainsamples, valsamples, testsamples = slices(tplusv, [train_size, val_size, test_size], generator=torch.Generator().manual_seed(42))
enablecuda = True
notenablecuda = False
noprocesses = 2
abstrationtrain = loads(trainsamples)
# num_workers indicate how many processes to use for loading data
# pin_memory puts dataset in cuda memory
# abcd takes the train set and is a abstraction over a class that provides batches of the dataset when used in a for loop. It 
# breaks the data set into batches of mentioned batchsize.
abstrationval = loads(valsamples)
# num_workers indicate how many processes to use for loading data
# pin_memory puts dataset in cuda memory
# abcd takes the train set and is a abstraction over a class that provides batches of the dataset when used in a for loop. It 
# breaks the data set into batches of mentioned batchsize.

In [14]:
ibm = inbuiltmodel(pretrained=True)
# now we invoke the inbuilt vgg16 model. pretrained = True means that  we want trained model

In [15]:
disablegradientcomputation = False
for gg in ibm.parameters():
    gg.requires_grad = disablegradientcomputation
# here, we set requires_grad parameter of each to False so that its gradient is not calculated or updated
ibm.classifier = bunchoflayers( nn.Linear(ibm.classifier[0].in_features ,10), nn.Softmax(dim=1))

In [16]:
%pip install wandb -q
import wandb
!wandb login 48b05580d4310ecb5464f6144e2ac55789e9f8ec


wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


In [17]:
wandb.init(name='n1', 
           project='n2',
           notes='n3', 
           tags=['Fashion MNIST', 'Test Run'],
           entity='utkrisht')

In [18]:
ibm

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [19]:
 

lossfunc = nn.CrossEntropyLoss( )
reducefunc = torch.optim.Adam(ibm.classifier.parameters())

In [20]:
def convert_prob_to_exactvalues(generated, labels):
    useless2, yhat = torch.max(generated, dim=1)
    correct_tensor = yhat.eq(labels.data.view_as(yhat))
             
    return torch.mean(correct_tensor.type(torch.FloatTensor)).item()

In [21]:
def fitthemodel(model, lossfunc, reducefunc, trainset, valset, dumpmodelname, terminatetraining=10, n_epochs=1 ):
    consec_badresult = 0
    bestloss = np.Inf
     
    model.epochs = 0  
    siz = 100
     
    for epoch in range(0,n_epochs):        
        tloss, vloss, tscore, vscore = 0 , 0, 0, 0 
        model.train()
        for ii, (useless, labels) in enumerate(trainset):
            print('ii'+str(ii))
            data2 = pickle.load(open("drive/MyDrive/sem6/mlass2/"+str(ii)+"batch_train.sav", "rb") )
            
            # print('target')
            # print(target)
            
            
            reducefunc.zero_grad()
             
            data2 = data2.view(data2.size()[0], data2.size()[1]*data2.size()[2]*data2.size()[3])
            generated = model.classifier(data2)
            del data2
            gc.collect()
            loss = lossfunc(generated, labels)
            # print(type(loss))
            loss.backward()
            reducefunc.step()
            tloss = tloss + (loss.item() * siz)  
            convert_prob_to_exactvalues(generated, labels)

             
            tscore += convert_prob_to_exactvalues(generated, labels) * siz 
        else:
            model.epochs += 1            
            with torch.no_grad():
                model.eval() 
                for jj, (useless, labels) in enumerate(abstrationval):
                    data2 = pickle.load(open("drive/MyDrive/sem6/mlass2/"+str(jj+432)+"batch_train.sav", "rb") ) 
                    data2 = data2.view(data2.size()[0], data2.size()[1]*data2.size()[2]*data2.size()[3])          
                    generated = model.classifier(data2)
                    del data2
                    gc.collect()
                    loss = lossfunc(generated, labels)
                    vloss = vloss + (loss.item() * siz)                    
                    vscore += convert_prob_to_exactvalues(generated, labels) * siz 
                     

                asize, bsize = len(trainset.dataset), len(valset.dataset)
                # extracting train and validation no. of samples
                tloss,  vloss, tscore, vscore  = tloss / asize,   vloss / bsize, tscore / asize,  vscore / bsize  
                # Dividing all 4 metrics to compute avg.

                 
               
                wandb.log({"Epoch": epoch,        
           "Train Loss": tloss,        
           "Train Acc": tscore,        
           "Valid Loss": vloss,        
           "Valid Acc": vscore})
                print("epoch"+str(epoch+1))
                print("training loss:"+str(tloss))
                print("Val loss:"+str(vloss))
                print("train accuracy:"+str(tscore))
                print("val accuracy:"+str(vscore))     
                if bestloss  > vloss:
                    
                    torch.save(model.state_dict(), dumpmodelname)
                    consec_badresult = 0
                    bestloss = vloss
                else:
                    consec_badresult += 1
                    if terminatetraining <= consec_badresult:
                        print("no more training needed")
                        model.load_state_dict(torch.load(dumpmodelname))
                        model.optimizer = reducefunc
                        return model
    model.optimizer = reducefunc
    return model

In [22]:
trained_model = fitthemodel(ibm, lossfunc, reducefunc, abstrationtrain, 
                                        abstrationval, "mymodel.pt", n_epochs=3)


ii0
ii1
ii2
ii3
ii4
ii5
ii6
ii7
ii8
ii9
ii10
ii11
ii12
ii13
ii14
ii15
ii16
ii17
ii18
ii19
ii20
ii21
ii22
ii23
ii24
ii25
ii26
ii27
ii28
ii29
ii30
ii31
ii32
ii33
ii34
ii35
ii36
ii37
ii38
ii39
ii40
ii41
ii42
ii43
ii44
ii45
ii46
ii47
ii48
ii49
ii50
ii51
ii52
ii53
ii54
ii55
ii56
ii57
ii58
ii59
ii60
ii61
ii62
ii63
ii64
ii65
ii66
ii67
ii68
ii69
ii70
ii71
ii72
ii73
ii74
ii75
ii76
ii77
ii78
ii79
ii80
ii81
ii82
ii83
ii84
ii85
ii86
ii87
ii88
ii89
ii90
ii91
ii92
ii93
ii94
ii95
ii96
ii97
ii98
ii99
ii100
ii101
ii102
ii103
ii104
ii105
ii106
ii107
ii108
ii109
ii110
ii111
ii112
ii113
ii114
ii115
ii116
ii117
ii118
ii119
ii120
ii121
ii122
ii123
ii124
ii125
ii126
ii127
ii128
ii129
ii130
ii131
ii132
ii133
ii134
ii135
ii136
ii137
ii138
ii139
ii140
ii141
ii142
ii143
ii144
ii145
ii146
ii147
ii148
ii149
ii150
ii151
ii152
ii153
ii154
ii155
ii156
ii157
ii158
ii159
ii160
ii161
ii162
ii163
ii164
ii165
ii166
ii167
ii168
ii169
ii170
ii171
ii172
ii173
ii174
ii175
ii176
ii177
ii178
ii179
ii180
ii181
ii182
ii183
ii184


In [23]:
wandb.finish()

In [ ]:
# import pickle 
# pickle.save(trained_model, open("drive/MyDrive/sem6/mlass2/model.sav", "wb") )

In [ ]:
# Whether to test on a gpu
from torch import cuda
trained_model = pickle.load(open("drive/MyDrive/sem6/mlass2/model.sav", "rb"))
 
gpuenabled =cuda.is_available()
print("find gpu"+str(cuda.is_available()))
if cuda.is_available():
    trained_model = trained_model.to('cuda')

find gpuTrue


In [ ]:
def yhat_acc(generated, label):
  useless3, yhat = torch.max(generated, dim=1) 
  acc = torch.mean(yhat.eq(label.data.view_as(yhat)).type(torch.FloatTensor))
  return acc.item(), yhat

In [ ]:
#  accuracy on test set
test_loader = abcd(testsamples, batch_size=collectiveset, shuffle=False, num_workers=2, pin_memory=True)
trained_model.eval()
test_acc = 0.0
pred_target = []
for jj, (data, label) in enumerate(test_loader):
  if gpuenabled:
    data, label = data.cuda(), label.cuda()
  generated = trained_model(data)
  

  accuracy, yhat = yhat_acc(generated, label) 
  # Multiply average accuracy times the number of examples
  pred_target.append([label,yhat])
  test_acc += accuracy * 100
test_acc = test_acc/len(test_loader.dataset)
print("test set accuracy:" + str(test_acc))

test set accuracy:0.920500002304713


In [ ]:
#confusion matrix on test set
import numpy as np
confusionmatrix = np.zeros(shape=(10,10))
for i in pred_target:
  # print(i[0])
  for j in range(len(i[0])):
    actual = i[0][j].item()
    predicted = i[1][j].item()
    confusionmatrix[actual][predicted] += 1

print(confusionmatrix)

[[562.   0.  13.  18.   1.   0.  61.   0.   3.   0.]
 [  0. 601.   0.   8.   2.   0.   0.   0.   0.   0.]
 [  7.   1. 549.   4.  14.   0.  35.   0.   2.   0.]
 [  7.   3.   2. 530.  11.   0.   9.   0.   0.   0.]
 [  3.   1.  20.  29. 517.   0.  37.   0.   0.   0.]
 [  0.   0.   0.   1.   0. 591.   0.  13.   0.   8.]
 [ 54.   0.  27.  27.  12.   0. 477.   0.   3.   0.]
 [  0.   0.   0.   0.   0.   2.   0. 518.   0.  17.]
 [  0.   0.   0.   2.   0.   1.   5.   0. 590.   0.]
 [  0.   0.   0.   0.   0.   3.   0.  11.   0. 588.]]


In [ ]:
#classwise confusion matrix and accuracy on test set
# print(np.sum(confusionmatrix))
for classwise in range(10):
  print("for class "+str(classwise))
  # print(confusionmatrix[classwise])
  acc = confusionmatrix[classwise][classwise] / np.sum(confusionmatrix[classwise])
  print("accuracy:"+str(acc) )
  mat = np.zeros(shape=(2,2))
  mat[0][0], mat[0][1] = confusionmatrix[classwise][classwise],  sum(confusionmatrix[classwise]) -  confusionmatrix[classwise][classwise]
  mat[1][0] = sum(confusionmatrix.T[classwise]) -  confusionmatrix[classwise][classwise]
  mat[1][1] = np.sum(confusionmatrix) - mat[0][0] - mat[0][1] - mat[1][0]
  print("confusion matrix")
  print(mat)
  

for class 0
accuracy:0.8541033434650456
confusion matrix
[[ 562.   96.]
 [  71. 5271.]]
for class 1
accuracy:0.983633387888707
confusion matrix
[[6.010e+02 1.000e+01]
 [5.000e+00 5.384e+03]]
for class 2
accuracy:0.8970588235294118
confusion matrix
[[ 549.   63.]
 [  62. 5326.]]
for class 3
accuracy:0.9430604982206405
confusion matrix
[[ 530.   32.]
 [  89. 5349.]]
for class 4
accuracy:0.8517298187808896
confusion matrix
[[ 517.   90.]
 [  40. 5353.]]
for class 5
accuracy:0.964110929853181
confusion matrix
[[ 591.   22.]
 [   6. 5381.]]
for class 6
accuracy:0.795
confusion matrix
[[ 477.  123.]
 [ 147. 5253.]]
for class 7
accuracy:0.9646182495344506
confusion matrix
[[ 518.   19.]
 [  24. 5439.]]
for class 8
accuracy:0.9866220735785953
confusion matrix
[[ 590.    8.]
 [   8. 5394.]]
for class 9
accuracy:0.9767441860465116
confusion matrix
[[ 588.   14.]
 [  25. 5373.]]


In [ ]:
f=open("Q2logs.txt", "r")
r = f.readlines()
tloss = []
vloss = []
tacc = []
vacc = []
for i in r:
    if "Training Loss" in i:
        st = i.split("|")
        tloss.append(float(st[3].strip()))
        vloss.append(float(st[6].strip()))
        tacc.append(float(st[4].strip()[:-1]))
        vacc.append(float(st[7].strip()[:-1]))
print(len(tloss))
print(len(vloss))
print(len(tacc))
print(len(vacc))
        
    

26
26
26
26


In [ ]:
#plotting loss with epochs
import matplotlib.pyplot as plt
plt.plot(tloss,label="training loss")
plt.plot(vloss,label="validation loss")
plt.legend(loc="upper left")
plt.savefig("result.png")
plt.close()

plt.plot(tacc,label="training accuracy")
plt.plot(vacc,label="validation accuracy")
plt.legend(loc="upper left")
plt.savefig("result2.png")
plt.close()
